### ISSUE TITLE
Failed when running the test of your PRA.

### ISSUE THREAD

**Issue by meloncolie** [wliu88/AttentivePathRanking#2]
Following your brief introduction of running PRA test, 2 test cases failed out of 159 in total. Do you have any suggestions to solve this problem?

```
git clone git@github.com:wliu88/pra_scala.git
cd pra_scala
sbt test
```

```
[info] ScalaTest
[info] Run completed in 6 seconds, 729 milliseconds.
[info] Total number of tests run: 159
[info] Suites: completed 26, aborted 0
[info] Tests: succeeded 157, failed 2, canceled 0, ignored 0, pending 0
[info] *** 2 TESTS FAILED ***
[error] Failed: Total 183, Failed 2, Errors 0, Passed 181
[error] Failed tests:
[error]         edu.cmu.ml.rtw.pra.features.LexicalizedPathTypeSpec
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 8 s, completed Nov 9, 2020 5:21:35 PM
```

**Comment by wliu88** [comment]
I have seen the same error message recently when installing the pra code. However, this error has not affected our experiment. You could move forward with the experiment and see if you encountered any further issues.

**Comment by meloncolie** [comment]
> I have seen the same error message recently when installing the pra code. However, this error has not affected our experiment. You could move forward with the experiment and see if you encountered any further issues.

thank you for your reply, I will try the experiments firstly. All testing cases in original repo are passed, hopefully this error message in your repo could be fixed in the future.😊
